// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_session.proto

package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceSessionPBChannel struct {
	// Frequency (Hz).
	Frequency uint32 `protobuf:"varint,1,opt,name=frequency" json:"frequency,omitempty"`
	// Min. data-rate.
	MinDr uint32 `protobuf:"varint,2,opt,name=min_dr,json=minDr" json:"min_dr,omitempty"`
	// Max. data-rate.
	MaxDr                uint32   `protobuf:"varint,3,opt,name=max_dr,json=maxDr" json:"max_dr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceSessionPBChannel) Reset()         { *m = DeviceSessionPBChannel{} }
func (m *DeviceSessionPBChannel) String() string { return proto.CompactTextString(m) }
func (*DeviceSessionPBChannel) ProtoMessage()    {}
func (*DeviceSessionPBChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_session_437a4089955d87a2, []int{0}
}
func (m *DeviceSessionPBChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSessionPBChannel.Unmarshal(m, b)
}
func (m *DeviceSessionPBChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSessionPBChannel.Marshal(b, m, deterministic)
}
func (dst *DeviceSessionPBChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSessionPBChannel.Merge(dst, src)
}
func (m *DeviceSessionPBChannel) XXX_Size() int {
	return xxx_messageInfo_DeviceSessionPBChannel.Size(m)
}
func (m *DeviceSessionPBChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSessionPBChannel.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSessionPBChannel proto.InternalMessageInfo

func (m *DeviceSessionPBChannel) GetFrequency() uint32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *DeviceSessionPBChannel) GetMinDr() uint32 {
	if m != nil {
		return m.MinDr
	}
	return 0
}

func (m *DeviceSessionPBChannel) GetMaxDr() uint32 {
	if m != nil {
		return m.MaxDr
	}
	return 0
}

type DeviceSessionPBUplinkADRHistory struct {
	// Uplink frame-counter.
	FCnt uint32 `protobuf:"varint,1,opt,name=f_cnt,json=fCnt" json:"f_cnt,omitempty"`
	// Max SNR (of deduplicated frames received by one or multiple gateways).
	MaxSnr float32 `protobuf:"fixed32,2,opt,name=max_snr,json=maxSnr" json:"max_snr,omitempty"`
	// TX Power (as known by the network-server).
	TxPowerIndex uint32 `protobuf:"varint,3,opt,name=tx_power_index,json=txPowerIndex" json:"tx_power_index,omitempty"`
	// Number of receiving gateways.
	GatewayCount         uint32   `protobuf:"varint,4,opt,name=gateway_count,json=gatewayCount" json:"gateway_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceSessionPBUplinkADRHistory) Reset()         { *m = DeviceSessionPBUplinkADRHistory{} }
func (m *DeviceSessionPBUplinkADRHistory) String() string { return proto.CompactTextString(m) }
func (*DeviceSessionPBUplinkADRHistory) ProtoMessage()    {}
func (*DeviceSessionPBUplinkADRHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_session_437a4089955d87a2, []int{1}
}
func (m *DeviceSessionPBUplinkADRHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSessionPBUplinkADRHistory.Unmarshal(m, b)
}
func (m *DeviceSessionPBUplinkADRHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSessionPBUplinkADRHistory.Marshal(b, m, deterministic)
}
func (dst *DeviceSessionPBUplinkADRHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSessionPBUplinkADRHistory.Merge(dst, src)
}
func (m *DeviceSessionPBUplinkADRHistory) XXX_Size() int {
	return xxx_messageInfo_DeviceSessionPBUplinkADRHistory.Size(m)
}
func (m *DeviceSessionPBUplinkADRHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSessionPBUplinkADRHistory.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSessionPBUplinkADRHistory proto.InternalMessageInfo

func (m *DeviceSessionPBUplinkADRHistory) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *DeviceSessionPBUplinkADRHistory) GetMaxSnr() float32 {
	if m != nil {
		return m.MaxSnr
	}
	return 0
}

func (m *DeviceSessionPBUplinkADRHistory) GetTxPowerIndex() uint32 {
	if m != nil {
		return m.TxPowerIndex
	}
	return 0
}

func (m *DeviceSessionPBUplinkADRHistory) GetGatewayCount() uint32 {
	if m != nil {
		return m.GatewayCount
	}
	return 0
}

type DeviceSessionPBUplinkGatewayHistory struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceSessionPBUplinkGatewayHistory) Reset()         { *m = DeviceSessionPBUplinkGatewayHistory{} }
func (m *DeviceSessionPBUplinkGatewayHistory) String() string { return proto.CompactTextString(m) }
func (*DeviceSessionPBUplinkGatewayHistory) ProtoMessage()    {}
func (*DeviceSessionPBUplinkGatewayHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_session_437a4089955d87a2, []int{2}
}
func (m *DeviceSessionPBUplinkGatewayHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSessionPBUplinkGatewayHistory.Unmarshal(m, b)
}
func (m *DeviceSessionPBUplinkGatewayHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSessionPBUplinkGatewayHistory.Marshal(b, m, deterministic)
}
func (dst *DeviceSessionPBUplinkGatewayHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSessionPBUplinkGatewayHistory.Merge(dst, src)
}
func (m *DeviceSessionPBUplinkGatewayHistory) XXX_Size() int {
	return xxx_messageInfo_DeviceSessionPBUplinkGatewayHistory.Size(m)
}
func (m *DeviceSessionPBUplinkGatewayHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSessionPBUplinkGatewayHistory.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSessionPBUplinkGatewayHistory proto.InternalMessageInfo

type DeviceSessionPB struct {
	// ID of the device-profile.
	DeviceProfileId string `protobuf:"bytes,1,opt,name=device_profile_id,json=deviceProfileId" json:"device_profile_id,omitempty"`
	// ID of the service-profile.
	ServiceProfileId string `protobuf:"bytes,2,opt,name=service_profile_id,json=serviceProfileId" json:"service_profile_id,omitempty"`
	// ID of the routing-profile.
	RoutingProfileId string `protobuf:"bytes,3,opt,name=routing_profile_id,json=routingProfileId" json:"routing_profile_id,omitempty"`
	// Device address.
	DevAddr []byte `protobuf:"bytes,4,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,5,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Join EUI.
	JoinEui []byte `protobuf:"bytes,6,opt,name=join_eui,json=joinEui,proto3" json:"join_eui,omitempty"`
	// FNwkSIntKey.
	FNwkSIntKey []byte `protobuf:"bytes,7,opt,name=f_nwk_s_int_key,json=fNwkSIntKey,proto3" json:"f_nwk_s_int_key,omitempty"`
	// SNwkSIntKey.
	SNwkSIntKey []byte `protobuf:"bytes,8,opt,name=s_nwk_s_int_key,json=sNwkSIntKey,proto3" json:"s_nwk_s_int_key,omitempty"`
	// NwkSEncKey.
	NwkSEncKey []byte `protobuf:"bytes,9,opt,name=nwk_s_enc_key,json=nwkSEncKey,proto3" json:"nwk_s_enc_key,omitempty"`
	// Uplink frame-counter.
	FCntUp uint32 `protobuf:"varint,10,opt,name=f_cnt_up,json=fCntUp" json:"f_cnt_up,omitempty"`
	// Downlink frame-counter (network-server).
	NFCntDown uint32 `protobuf:"varint,11,opt,name=n_f_cnt_down,json=nFCntDown" json:"n_f_cnt_down,omitempty"`
	// Uplink frame-counter (application-server).
	// Note: this frame-counter is managed by the application-server.
	AFCntDown uint32 `protobuf:"varint,12,opt,name=a_f_cnt_down,json=aFCntDown" json:"a_f_cnt_down,omitempty"`
	// Frame-counter holding the last confirmed downlink frame (n_f_cnt_down or a_f_cnt_down).
	ConfFCnt uint32 `protobuf:"varint,39,opt,name=conf_f_cnt,json=confFCnt" json:"conf_f_cnt,omitempty"`
	// Skip uplink frame-counter validation.
	SkipFCntCheck bool `protobuf:"varint,13,opt,name=skip_f_cnt_check,json=skipFCntCheck" json:"skip_f_cnt_check,omitempty"`
	// RX Delay.
	RxDelay uint32 `protobuf:"varint,14,opt,name=rx_delay,json=rxDelay" json:"rx_delay,omitempty"`
	// RX1 data-rate offset.
	Rx1DrOffset uint32 `protobuf:"varint,15,opt,name=rx1_dr_offset,json=rx1DrOffset" json:"rx1_dr_offset,omitempty"`
	// RX2 data-rate.
	Rx2Dr uint32 `protobuf:"varint,16,opt,name=rx2_dr,json=rx2Dr" json:"rx2_dr,omitempty"`
	// RX2 frequency.
	Rx2Frequency uint32 `protobuf:"varint,17,opt,name=rx2_frequency,json=rx2Frequency" json:"rx2_frequency,omitempty"`
	// TXPowerIndex which the node is using. The possible values are defined
	// by the lorawan/band package and are region specific. By default it is
	// assumed that the node is using TXPower 0. This value is controlled by
	// the ADR engine.
	TxPowerIndex uint32 `protobuf:"varint,18,opt,name=tx_power_index,json=txPowerIndex" json:"tx_power_index,omitempty"`
	// DR defines the (last known) data-rate at which the node is operating.
	// This value is controlled by the ADR engine.
	Dr uint32 `protobuf:"varint,19,opt,name=dr" json:"dr,omitempty"`
	// ADR defines if the device has ADR enabled.
	Adr bool `protobuf:"varint,20,opt,name=adr" json:"adr,omitempty"`
	// MaxSupportedTXPowerIndex defines the maximum supported tx-power index
	// by the node, or 0 when not set.
	MaxSupportedTxPowerIndex uint32 `protobuf:"varint,21,opt,name=max_supported_tx_power_index,json=maxSupportedTxPowerIndex" json:"max_supported_tx_power_index,omitempty"`
	// MaxSupportedDR defines the maximum supported DR index by the node,
	// or 0 when not set.
	MaxSupportedDr uint32 `protobuf:"varint,22,opt,name=max_supported_dr,json=maxSupportedDr" json:"max_supported_dr,omitempty"`
	// NbTrans defines the number of transmissions for each unconfirmed uplink
	// frame. In case of 0, the default value is used.
	// This value is controlled by the ADR engine.
	NbTrans uint32 `protobuf:"varint,23,opt,name=nb_trans,json=nbTrans" json:"nb_trans,omitempty"`
	// Channels that are activated on the device.
	EnabledUplinkChannels []uint32 `protobuf:"varint,24,rep,packed,name=enabled_uplink_channels,json=enabledUplinkChannels" json:"enabled_uplink_channels,omitempty"`
	// Extra uplink channels, configured by the user.
	ExtraUplinkChannels map[uint32]*DeviceSessionPBChannel `protobuf:"bytes,25,rep,name=extra_uplink_channels,json=extraUplinkChannels" json:"extra_uplink_channels,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Frequency of each channel.
	ChannelFrequencies []uint32 `protobuf:"varint,26,rep,packed,name=channel_frequencies,json=channelFrequencies" json:"channel_frequencies,omitempty"`
	// Uplink history for ADR (last 20 uplink transmissions).
	UplinkAdrHistory []*DeviceSessionPBUplinkADRHistory `protobuf:"bytes,27,rep,name=uplink_adr_history,json=uplinkAdrHistory" json:"uplink_adr_history,omitempty"`
	// Uplink gateway history (for Class B / C).
	// Note that as bytes are not supported in a Protobuf map, the gateway ID is HEX encoded.
	UplinkGatewayHistory map[string]*DeviceSessionPBUplinkGatewayHistory `protobuf:"bytes,28,rep,name=uplink_gateway_history,json=uplinkGatewayHistory" json:"uplink_gateway_history,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Last device-status requested timestamp (Unix ns)
	LastDeviceStatusRequestTimeUnixNs int64 `protobuf:"varint,29,opt,name=last_device_status_request_time_unix_ns,json=lastDeviceStatusRequestTimeUnixNs" json:"last_device_status_request_time_unix_ns,omitempty"`
	// Last device-status battery status.
	LastDeviceStatusBattery uint32 `protobuf:"varint,30,opt,name=last_device_status_battery,json=lastDeviceStatusBattery" json:"last_device_status_battery,omitempty"`
	// Last device-status margin status.
	LastDeviceStatusMargin int32 `protobuf:"varint,31,opt,name=last_device_status_margin,json=lastDeviceStatusMargin" json:"last_device_status_margin,omitempty"`
	// Last downlink timestamp (Unix ns).
	LastDownlinkTxTimestampUnixNs int64 `protobuf:"varint,32,opt,name=last_downlink_tx_timestamp_unix_ns,json=lastDownlinkTxTimestampUnixNs" json:"last_downlink_tx_timestamp_unix_ns,omitempty"`
	// Class-B beacon is locked.
	BeaconLocked bool `protobuf:"varint,33,opt,name=beacon_locked,json=beaconLocked" json:"beacon_locked,omitempty"`
	// Class-B ping-slot nb.
	PingSlotNb uint32 `protobuf:"varint,34,opt,name=ping_slot_nb,json=pingSlotNb" json:"ping_slot_nb,omitempty"`
	// Class-B ping-slot data-rate.
	PingSlotDr uint32 `protobuf:"varint,35,opt,name=ping_slot_dr,json=pingSlotDr" json:"ping_slot_dr,omitempty"`
	// Class-B ping-slot tx frequency.
	PingSlotFrequency uint32 `protobuf:"varint,36,opt,name=ping_slot_frequency,json=pingSlotFrequency" json:"ping_slot_frequency,omitempty"`
	// LoRaWAN mac-version.
	MacVersion string `protobuf:"bytes,37,opt,name=mac_version,json=macVersion" json:"mac_version,omitempty"`
	// MinSupportedTXPowerIndex defines the minimum supported tx-power index
	// by the node (default 0).
	MinSupportedTxPowerIndex uint32 `protobuf:"varint,38,opt,name=min_supported_tx_power_index,json=minSupportedTxPowerIndex" json:"min_supported_tx_power_index,omitempty"`
	// RejoinRequestMaxCountN defines the 2^(C+4) uplink message interval for
	// the rejoin-request.
	RejoinRequestMaxCountN uint32 `protobuf:"varint,40,opt,name=rejoin_request_max_count_n,json=rejoinRequestMaxCountN" json:"rejoin_request_max_count_n,omitempty"`
	// RejoinRequestMaxTimeN defines the 2^(T+10) time interval (seconds)
	// for the rejoin-request.
	RejoinRequestMaxTimeN uint32 `protobuf:"varint,41,opt,name=rejoin_request_max_time_n,json=rejoinRequestMaxTimeN" json:"rejoin_request_max_time_n,omitempty"`
	// Rejoin counter (RJCount0).
	// This counter is reset to 0 after each successful join-accept.
	RejoinCount_0 uint32 `protobuf:"varint,42,opt,name=rejoin_count_0,json=rejoinCount0" json:"rejoin_count_0,omitempty"`
	// Pending rejoin device-session contains a device-session which has not
	// yet been activated by the device (by sending a first uplink).
	PendingRejoinDeviceSession []byte   `protobuf:"bytes,43,opt,name=pending_rejoin_device_session,json=pendingRejoinDeviceSession,proto3" json:"pending_rejoin_device_session,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *DeviceSessionPB) Reset()         { *m = DeviceSessionPB{} }
func (m *DeviceSessionPB) String() string { return proto.CompactTextString(m) }
func (*DeviceSessionPB) ProtoMessage()    {}
func (*DeviceSessionPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_session_437a4089955d87a2, []int{3}
}
func (m *DeviceSessionPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSessionPB.Unmarshal(m, b)
}
func (m *DeviceSessionPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSessionPB.Marshal(b, m, deterministic)
}
func (dst *DeviceSessionPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSessionPB.Merge(dst, src)
}
func (m *DeviceSessionPB) XXX_Size() int {
	return xxx_messageInfo_DeviceSessionPB.Size(m)
}
func (m *DeviceSessionPB) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSessionPB.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSessionPB proto.InternalMessageInfo

func (m *DeviceSessionPB) GetDeviceProfileId() string {
	if m != nil {
		return m.DeviceProfileId
	}
	return ""
}

func (m *DeviceSessionPB) GetServiceProfileId() string {
	if m != nil {
		return m.ServiceProfileId
	}
	return ""
}

func (m *DeviceSessionPB) GetRoutingProfileId() string {
	if m != nil {
		return m.RoutingProfileId
	}
	return ""
}

func (m *DeviceSessionPB) GetDevAddr() []byte {
	if m != nil {
		return m.DevAddr
	}
	return nil
}

func (m *DeviceSessionPB) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *DeviceSessionPB) GetJoinEui() []byte {
	if m != nil {
		return m.JoinEui
	}
	return nil
}

func (m *DeviceSessionPB) GetFNwkSIntKey() []byte {
	if m != nil {
		return m.FNwkSIntKey
	}
	return nil
}

func (m *DeviceSessionPB) GetSNwkSIntKey() []byte {
	if m != nil {
		return m.SNwkSIntKey
	}
	return nil
}

func (m *DeviceSessionPB) GetNwkSEncKey() []byte {
	if m != nil {
		return m.NwkSEncKey
	}
	return nil
}

func (m *DeviceSessionPB) GetFCntUp() uint32 {
	if m != nil {
		return m.FCntUp
	}
	return 0
}

func (m *DeviceSessionPB) GetNFCntDown() uint32 {
	if m != nil {
		return m.NFCntDown
	}
	return 0
}

func (m *DeviceSessionPB) GetAFCntDown() uint32 {
	if m != nil {
		return m.AFCntDown
	}
	return 0
}

func (m *DeviceSessionPB) GetConfFCnt() uint32 {
	if m != nil {
		return m.ConfFCnt
	}
	return 0
}

func (m *DeviceSessionPB) GetSkipFCntCheck() bool {
	if m != nil {
		return m.SkipFCntCheck
	}
	return false
}

func (m *DeviceSessionPB) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *DeviceSessionPB) GetRx1DrOffset() uint32 {
	if m != nil {
		return m.Rx1DrOffset
	}
	return 0
}

func (m *DeviceSessionPB) GetRx2Dr() uint32 {
	if m != nil {
		return m.Rx2Dr
	}
	return 0
}

func (m *DeviceSessionPB) GetRx2Frequency() uint32 {
	if m != nil {
		return m.Rx2Frequency
	}
	return 0
}

func (m *DeviceSessionPB) GetTxPowerIndex() uint32 {
	if m != nil {
		return m.TxPowerIndex
	}
	return 0
}

func (m *DeviceSessionPB) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *DeviceSessionPB) GetAdr() bool {
	if m != nil {
		return m.Adr
	}
	return false
}

func (m *DeviceSessionPB) GetMaxSupportedTxPowerIndex() uint32 {
	if m != nil {
		return m.MaxSupportedTxPowerIndex
	}
	return 0
}

func (m *DeviceSessionPB) GetMaxSupportedDr() uint32 {
	if m != nil {
		return m.MaxSupportedDr
	}
	return 0
}

func (m *DeviceSessionPB) GetNbTrans() uint32 {
	if m != nil {
		return m.NbTrans
	}
	return 0
}

func (m *DeviceSessionPB) GetEnabledUplinkChannels() []uint32 {
	if m != nil {
		return m.EnabledUplinkChannels
	}
	return nil
}

func (m *DeviceSessionPB) GetExtraUplinkChannels() map[uint32]*DeviceSessionPBChannel {
	if m != nil {
		return m.ExtraUplinkChannels
	}
	return nil
}

func (m *DeviceSessionPB) GetChannelFrequencies() []uint32 {
	if m != nil {
		return m.ChannelFrequencies
	}
	return nil
}

func (m *DeviceSessionPB) GetUplinkAdrHistory() []*DeviceSessionPBUplinkADRHistory {
	if m != nil {
		return m.UplinkAdrHistory
	}
	return nil
}

func (m *DeviceSessionPB) GetUplinkGatewayHistory() map[string]*DeviceSessionPBUplinkGatewayHistory {
	if m != nil {
		return m.UplinkGatewayHistory
	}
	return nil
}

func (m *DeviceSessionPB) GetLastDeviceStatusRequestTimeUnixNs() int64 {
	if m != nil {
		return m.LastDeviceStatusRequestTimeUnixNs
	}
	return 0
}

func (m *DeviceSessionPB) GetLastDeviceStatusBattery() uint32 {
	if m != nil {
		return m.LastDeviceStatusBattery
	}
	return 0
}

func (m *DeviceSessionPB) GetLastDeviceStatusMargin() int32 {
	if m != nil {
		return m.LastDeviceStatusMargin
	}
	return 0
}

func (m *DeviceSessionPB) GetLastDownlinkTxTimestampUnixNs() int64 {
	if m != nil {
		return m.LastDownlinkTxTimestampUnixNs
	}
	return 0
}

func (m *DeviceSessionPB) GetBeaconLocked() bool {
	if m != nil {
		return m.BeaconLocked
	}
	return false
}

func (m *DeviceSessionPB) GetPingSlotNb() uint32 {
	if m != nil {
		return m.PingSlotNb
	}
	return 0
}

func (m *DeviceSessionPB) GetPingSlotDr() uint32 {
	if m != nil {
		return m.PingSlotDr
	}
	return 0
}

func (m *DeviceSessionPB) GetPingSlotFrequency() uint32 {
	if m != nil {
		return m.PingSlotFrequency
	}
	return 0
}

func (m *DeviceSessionPB) GetMacVersion() string {
	if m != nil {
		return m.MacVersion
	}
	return ""
}

func (m *DeviceSessionPB) GetMinSupportedTxPowerIndex() uint32 {
	if m != nil {
		return m.MinSupportedTxPowerIndex
	}
	return 0
}

func (m *DeviceSessionPB) GetRejoinRequestMaxCountN() uint32 {
	if m != nil {
		return m.RejoinRequestMaxCountN
	}
	return 0
}

func (m *DeviceSessionPB) GetRejoinRequestMaxTimeN() uint32 {
	if m != nil {
		return m.RejoinRequestMaxTimeN
	}
	return 0
}

func (m *DeviceSessionPB) GetRejoinCount_0() uint32 {
	if m != nil {
		return m.RejoinCount_0
	}
	return 0
}

func (m *DeviceSessionPB) GetPendingRejoinDeviceSession() []byte {
	if m != nil {
		return m.PendingRejoinDeviceSession
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceSessionPBChannel)(nil), "storage.DeviceSessionPBChannel")
	proto.RegisterType((*DeviceSessionPBUplinkADRHistory)(nil), "storage.DeviceSessionPBUplinkADRHistory")
	proto.RegisterType((*DeviceSessionPBUplinkGatewayHistory)(nil), "storage.DeviceSessionPBUplinkGatewayHistory")
	proto.RegisterType((*DeviceSessionPB)(nil), "storage.DeviceSessionPB")
	proto.RegisterMapType((map[uint32]*DeviceSessionPBChannel)(nil), "storage.DeviceSessionPB.ExtraUplinkChannelsEntry")
	proto.RegisterMapType((map[string]*DeviceSessionPBUplinkGatewayHistory)(nil), "storage.DeviceSessionPB.UplinkGatewayHistoryEntry")
}

func init() {
	proto.RegisterFile("device_session.proto", fileDescriptor_device_session_437a4089955d87a2)
}

var fileDescriptor_device_session_437a4089955d87a2 = []byte{
	// 1148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x96, 0x6f, 0x53, 0x1b, 0xb7,
	0x13, 0xc7, 0xc7, 0x10, 0xfe, 0x2d, 0x36, 0x18, 0x11, 0x40, 0xf8, 0x47, 0x7e, 0x38, 0x26, 0x69,
	0xdc, 0x34, 0x43, 0x13, 0x77, 0xda, 0x49, 0xd3, 0x99, 0xce, 0x10, 0x4c, 0x5a, 0xa6, 0x0d, 0xcd,
	0x1c, 0x24, 0x4f, 0x35, 0xf2, 0x49, 0x86, 0xab, 0x6d, 0xdd, 0x55, 0xa7, 0xb3, 0xcf, 0x6f, 0xa5,
	0x8f, 0xfb, 0x42, 0x3b, 0x5a, 0xc9, 0xf8, 0x0f, 0x76, 0x9f, 0xd9, 0xfb, 0xfd, 0xec, 0xae, 0x56,
	0xd2, 0xae, 0x0e, 0x1e, 0x0b, 0xd9, 0x8f, 0x42, 0xc9, 0x52, 0x99, 0xa6, 0x51, 0xac, 0x4e, 0x13,
	0x1d, 0x9b, 0x98, 0xac, 0xa5, 0x26, 0xd6, 0xfc, 0x56, 0xd6, 0x04, 0xec, 0x37, 0x11, 0xb8, 0x76,
	0xfa, 0xa7, 0xf7, 0xe7, 0x77, 0x5c, 0x29, 0xd9, 0x25, 0x47, 0xb0, 0xd1, 0xd6, 0xf2, 0xaf, 0x4c,
	0xaa, 0x70, 0x48, 0x0b, 0xd5, 0x42, 0xbd, 0x14, 0x8c, 0x0d, 0x64, 0x0f, 0x56, 0x7b, 0x91, 0x62,
	0x42, 0xd3, 0x25, 0x94, 0x56, 0x7a, 0x91, 0x6a, 0x6a, 0x34, 0xf3, 0xdc, 0x9a, 0x97, 0xbd, 0x99,
	0xe7, 0x4d, 0x5d, 0xfb, 0xbb, 0x00, 0xc7, 0x33, 0x69, 0x3e, 0x27, 0xdd, 0x48, 0x75, 0xce, 0x9a,
	0xc1, 0xaf, 0x91, 0x5d, 0xcb, 0x90, 0xec, 0xc2, 0x4a, 0x9b, 0x85, 0xca, 0xf8, 0x5c, 0x8f, 0xda,
	0xe7, 0xca, 0x90, 0x03, 0x58, 0xb3, 0xf1, 0x52, 0xe5, 0xf2, 0x2c, 0x05, 0x36, 0xfc, 0xb5, 0xd2,
	0xe4, 0x19, 0x6c, 0x99, 0x9c, 0x25, 0xf1, 0x40, 0x6a, 0x16, 0x29, 0x21, 0x73, 0x9f, 0xb0, 0x68,
	0xf2, 0x4f, 0xd6, 0x78, 0x69, 0x6d, 0xe4, 0x04, 0x4a, 0xb7, 0xdc, 0xc8, 0x01, 0x1f, 0xb2, 0x30,
	0xce, 0x94, 0xa1, 0x8f, 0x1c, 0xe4, 0x8d, 0xe7, 0xd6, 0x56, 0x7b, 0x0e, 0x27, 0x73, 0xd7, 0xf6,
	0x8b, 0x83, 0xfc, 0xfa, 0x6a, 0xff, 0xec, 0xc0, 0xf6, 0x0c, 0x47, 0x5e, 0xc2, 0x8e, 0xdf, 0xde,
	0x44, 0xc7, 0xed, 0xa8, 0x2b, 0x59, 0x24, 0x70, 0xfd, 0x1b, 0xc1, 0xb6, 0x13, 0x3e, 0x39, 0xfb,
	0xa5, 0x20, 0xaf, 0x80, 0xa4, 0x52, 0xcf, 0xc2, 0x4b, 0x08, 0x97, 0xbd, 0x32, 0x45, 0xeb, 0x38,
	0x33, 0x91, 0xba, 0x9d, 0xa4, 0x97, 0x1d, 0xed, 0x95, 0x31, 0x7d, 0x08, 0xeb, 0x42, 0xf6, 0x19,
	0x17, 0x42, 0x63, 0x89, 0xc5, 0x60, 0x4d, 0xc8, 0xfe, 0x99, 0x10, 0xda, 0xee, 0xa0, 0x95, 0x64,
	0x16, 0xd1, 0x15, 0x54, 0x56, 0x85, 0xec, 0x5f, 0x64, 0x91, 0xf5, 0xf9, 0x33, 0x8e, 0x14, 0x2a,
	0xab, 0xce, 0xc7, 0xfe, 0xb7, 0xd2, 0x33, 0xd8, 0x6e, 0x33, 0x35, 0xe8, 0xb0, 0x94, 0x45, 0xca,
	0xb0, 0x8e, 0x1c, 0xd2, 0x35, 0x24, 0x36, 0xdb, 0x57, 0x83, 0xce, 0xf5, 0xa5, 0x32, 0xbf, 0xc9,
	0xa1, 0xa5, 0xd2, 0x19, 0x6a, 0xdd, 0x51, 0xe9, 0x04, 0xf5, 0x14, 0x4a, 0x8e, 0x91, 0x2a, 0x44,
	0x66, 0x03, 0x19, 0x50, 0x83, 0xce, 0xf5, 0x85, 0x0a, 0x2d, 0x42, 0x61, 0x1d, 0x4f, 0x9e, 0x65,
	0x09, 0x05, 0x3c, 0xa0, 0x55, 0x7b, 0xf8, 0x9f, 0x13, 0x72, 0x0c, 0x45, 0xc5, 0x9c, 0x26, 0xe2,
	0x81, 0xa2, 0x9b, 0xee, 0x1a, 0xaa, 0x0f, 0xe7, 0xca, 0x34, 0xe3, 0x81, 0xb2, 0x00, 0x9f, 0x04,
	0x8a, 0x0e, 0xe0, 0xf7, 0xc0, 0x11, 0x40, 0x18, 0xab, 0xb6, 0x63, 0xe8, 0x0b, 0x94, 0xd7, 0xad,
	0xc5, 0x12, 0xe4, 0x05, 0x94, 0xd3, 0x4e, 0x94, 0xf8, 0x08, 0xe1, 0x9d, 0x0c, 0x3b, 0xb4, 0x54,
	0x2d, 0xd4, 0xd7, 0x83, 0x92, 0xb5, 0x5b, 0xe6, 0xdc, 0x1a, 0xed, 0x66, 0xe9, 0x9c, 0x09, 0xd9,
	0xe5, 0x43, 0xba, 0x85, 0x41, 0xd6, 0x74, 0xde, 0xb4, 0x7f, 0x49, 0x0d, 0x4a, 0x3a, 0x7f, 0xc3,
	0x84, 0x66, 0x71, 0xbb, 0x9d, 0x4a, 0x43, 0xb7, 0x51, 0xdf, 0xd4, 0xf9, 0x9b, 0xa6, 0xfe, 0x03,
	0x4d, 0xb6, 0x2d, 0x74, 0xde, 0xb0, 0x6d, 0x51, 0x76, 0x6d, 0xa1, 0xf3, 0x46, 0x53, 0xdb, 0xeb,
	0x69, 0xcd, 0xe3, 0x36, 0xdb, 0x71, 0xd7, 0x53, 0xe7, 0x8d, 0x0f, 0xf7, 0x9d, 0xf6, 0xf0, 0xa6,
	0x93, 0x39, 0x37, 0x7d, 0x0b, 0x96, 0x84, 0xa6, 0xbb, 0xa8, 0x2c, 0x09, 0x4d, 0xca, 0xb0, 0xcc,
	0x85, 0xa6, 0x8f, 0xb1, 0x18, 0xfb, 0x93, 0xfc, 0x0c, 0x47, 0xd8, 0x4a, 0x59, 0x92, 0xc4, 0xda,
	0x48, 0xc1, 0x66, 0xa2, 0xee, 0xa1, 0x2f, 0xb5, 0xfd, 0x35, 0x42, 0x6e, 0x26, 0x33, 0xd4, 0xa1,
	0x3c, 0xed, 0x2f, 0x34, 0xdd, 0x47, 0x9f, 0xad, 0x49, 0x9f, 0xa6, 0xb6, 0x9b, 0xa5, 0x5a, 0xcc,
	0x68, 0xae, 0x52, 0x7a, 0xe0, 0x36, 0x4b, 0xb5, 0x6e, 0xec, 0x5f, 0xf2, 0x03, 0x1c, 0x48, 0xc5,
	0x5b, 0x5d, 0x29, 0x58, 0x86, 0x4d, 0xc6, 0x42, 0x37, 0x6e, 0x52, 0x4a, 0xab, 0xcb, 0xf5, 0x52,
	0xb0, 0xe7, 0x65, 0xd7, 0x82, 0x7e, 0x16, 0xa5, 0x44, 0xc2, 0x9e, 0xcc, 0x8d, 0xe6, 0x0f, 0xbc,
	0x0e, 0xab, 0xcb, 0xf5, 0xcd, 0xc6, 0x9b, 0x53, 0x3f, 0xcf, 0x4e, 0x67, 0x3a, 0xf4, 0xf4, 0xc2,
	0x7a, 0x4d, 0x07, 0xbb, 0x50, 0x46, 0x0f, 0x83, 0x5d, 0xf9, 0x50, 0x21, 0xdf, 0xc2, 0xae, 0x8f,
	0x7c, 0x7f, 0x28, 0x91, 0x4c, 0x69, 0x05, 0x97, 0x46, 0xbc, 0xf4, 0x61, 0xac, 0x90, 0x2f, 0x40,
	0xfc, 0x8a, 0xb8, 0xd0, 0xec, 0xce, 0x8d, 0x0a, 0xfa, 0x3f, 0x5c, 0x54, 0x7d, 0xd1, 0xa2, 0x66,
	0x47, 0x5f, 0x50, 0x76, 0x31, 0xce, 0x84, 0x1e, 0x0d, 0xc3, 0x3b, 0xd8, 0xf7, 0x71, 0x47, 0xf3,
	0x6b, 0x14, 0xfb, 0x08, 0x63, 0x37, 0x16, 0x16, 0x3c, 0x6f, 0x76, 0xb9, 0x8a, 0x1f, 0x67, 0x73,
	0x24, 0x12, 0xc0, 0x8b, 0x2e, 0x4f, 0x0d, 0x1b, 0x3d, 0x13, 0x86, 0x9b, 0x2c, 0x65, 0x58, 0x62,
	0x6a, 0x98, 0x89, 0x7a, 0x92, 0x65, 0x2a, 0xca, 0x99, 0x4a, 0xe9, 0x93, 0x6a, 0xa1, 0xbe, 0x1c,
	0x3c, 0xb5, 0xb8, 0xcf, 0x8a, 0x70, 0xe0, 0xd8, 0x9b, 0xa8, 0x27, 0x3f, 0xab, 0x28, 0xbf, 0x4a,
	0xc9, 0x4f, 0x50, 0x99, 0x13, 0xb3, 0xc5, 0x8d, 0x91, 0x7a, 0x48, 0xff, 0x8f, 0x57, 0xe2, 0x60,
	0x36, 0xcc, 0x7b, 0x27, 0x93, 0x1f, 0xe1, 0x70, 0x8e, 0x73, 0x8f, 0xeb, 0xdb, 0x48, 0xd1, 0xe3,
	0x6a, 0xa1, 0xbe, 0x12, 0xec, 0xcf, 0xfa, 0x7e, 0x44, 0x95, 0x5c, 0x42, 0xcd, 0xb9, 0xc6, 0x03,
	0x85, 0x9b, 0x67, 0x72, 0xac, 0x20, 0x35, 0xbc, 0x97, 0xdc, 0x97, 0x51, 0xc5, 0x32, 0x9e, 0x60,
	0x0c, 0x0f, 0xde, 0xe4, 0x37, 0x23, 0xcc, 0x97, 0x70, 0x02, 0xa5, 0x96, 0xe4, 0x61, 0xac, 0x58,
	0x37, 0x0e, 0x3b, 0x52, 0xd0, 0xa7, 0xd8, 0x49, 0x45, 0x67, 0xfc, 0x1d, 0x6d, 0xa4, 0x0a, 0xc5,
	0xc4, 0x4e, 0xe8, 0xb4, 0x1b, 0x1b, 0xa6, 0x5a, 0xb4, 0x86, 0x95, 0x81, 0xb5, 0x5d, 0x77, 0x63,
	0x73, 0xd5, 0x9a, 0x26, 0x84, 0xa6, 0x27, 0xd3, 0x44, 0x53, 0x93, 0x53, 0xd8, 0x1d, 0x13, 0xe3,
	0x49, 0xf0, 0x0c, 0xc1, 0x9d, 0x11, 0x38, 0x1e, 0x07, 0xc7, 0xb0, 0xd9, 0xe3, 0x21, 0xeb, 0x4b,
	0x6d, 0x0f, 0x9c, 0x3e, 0xc7, 0x17, 0x01, 0x7a, 0x3c, 0xfc, 0xe2, 0x2c, 0xd8, 0xe7, 0x91, 0x5a,
	0xdc, 0xe7, 0x5f, 0xf9, 0x3e, 0x8f, 0xd4, 0xfc, 0x3e, 0x7f, 0x07, 0x15, 0x2d, 0xf1, 0x65, 0x18,
	0x5d, 0x02, 0xdb, 0xf6, 0xf8, 0x7c, 0x32, 0x45, 0xeb, 0xe8, 0xbd, 0xef, 0x08, 0x7f, 0xf2, 0x1f,
	0x79, 0x8e, 0x2f, 0xe9, 0x15, 0x79, 0x0b, 0x87, 0x73, 0x7c, 0xf1, 0x12, 0x29, 0xfa, 0x35, 0xba,
	0xee, 0xcd, 0xba, 0xda, 0x9d, 0xbf, 0xb2, 0x53, 0xce, 0x7b, 0xba, 0x4c, 0xaf, 0xe9, 0x4b, 0x3f,
	0x0b, 0xd1, 0x8a, 0xf1, 0x5f, 0x93, 0x33, 0x78, 0x92, 0x48, 0x25, 0xec, 0x7e, 0x79, 0x7a, 0xfa,
	0xeb, 0x86, 0x7e, 0x83, 0x8f, 0x4b, 0xc5, 0x43, 0x01, 0x32, 0x53, 0x1d, 0x52, 0xb9, 0x05, 0xba,
	0x68, 0x26, 0xd8, 0xa1, 0x69, 0x5f, 0x28, 0xf7, 0x01, 0x62, 0x7f, 0x92, 0xef, 0x61, 0xa5, 0xcf,
	0xbb, 0x99, 0xc4, 0x77, 0x7a, 0xb3, 0x71, 0xbc, 0xa8, 0xed, 0x7c, 0x9c, 0xc0, 0xd1, 0xef, 0x96,
	0xde, 0x16, 0x2a, 0x19, 0x1c, 0x2e, 0xec, 0xc5, 0xc9, 0x4c, 0x1b, 0x2e, 0xd3, 0xfb, 0xe9, 0x4c,
	0xaf, 0xfe, 0x7b, 0x78, 0x4c, 0xc7, 0x9c, 0x48, 0xdb, 0x5a, 0xc5, 0x0f, 0xbc, 0xef, 0xfe, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x4e, 0xf5, 0xad, 0x64, 0xf8, 0x09, 0x00, 0x00,
}
